adminPanel/urls.py
from django.urls import path
from .views import login_view, logout_view
from . import views

app_name = 'adminPanel'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', login_view, name='login'),
    path('registro/', views.registra_usuario, name='registrar_usuario'),
    path('logout/', logout_view, name='logout'),
    path('users/', views.users, name='users'),
    path('users/crear_usuario/', views.crear_usuario, name='crear_usuario'),
    path('users/editar_usuario/', views.editar_usuario, name='editar_usuario'),
    path('users/editar_usuario/<int:usuario_id>/', views.editar_usuario, name='editar_usuario'),
    path('users/eliminar_usuario/<int:usuario_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('productos', views.productos, name='productos'),
    path('productos/eliminar_producto/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path('productos/add-producto/', views.agregar_producto, name='crear_producto'),
    path('productos/editar_producto/<int:producto_id>/', views.editar_producto, name='editar_producto'),
    path('pedidos/', views.lista_pedidos, name='pedidos'),
    path('pedidos/actualizar_estado_pedido/<int:pedido_id>/', views.actualizar_estado_pedido, name='actualizar_estado_pedido'),
    
]

homePage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('promociones/', views.promociones, name='promociones'),
    path('contacto/', views.contacto, name='contacto'),
    path('carrito/', views.carrito, name='carrito'),
    path('carrito/guardar_pedido/', views.guardar_pedido, name='guardar_pedido'),
    path('productos/', views.productos, name='productos'),
    path('productos/<int:producto_id>/', views.ver_detalles_producto, name='ver_detalles_producto'),
    path('blog/', views.blog, name='blog'),
    path('blog/alfajor/', views.blogAlfajor, name='blogAlfajor'),
    path('blog/galleta_principe/', views.blogGalletaPrincipe, name='blogGalletaPrincipe'),
    path('blog/galleta/', views.blogGalleta, name='blogGalleta'),
]

webDuocPasteleria/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from homePage import views as homeViews
from adminPanel import views as adminViews

urlpatterns = [
    # urls de accedo
    path('admin/login/', adminViews.login_view, name='login'),
    path('admin/registro/', adminViews.registra_usuario, name='registrar_usuario'),

    # urls de la app
    path('admin/', include('adminPanel.urls')),
    path('admin/users/', adminViews.users, name='users'),
    path('admin/users/crear_usuario/', adminViews.crear_usuario, name='crear_usuario'),
    path('admin/users/editar_usuario/', adminViews.editar_usuario, name='editar_usuario'),
    path('admin/users/editar_usuario/<int:usuario_id>/', adminViews.editar_usuario, name='editar_usuario'),
    path('admin/users/eliminar_usuario/<int:usuario_id>/', adminViews.eliminar_usuario, name='eliminar_usuario'),
    path('admin/productos/', adminViews.productos, name='productos'),
    path('admin/productos/eliminar_producto/<int:producto_id>/', adminViews.eliminar_producto, name='eliminar_producto'),
    path('admin/productos/add-producto/', adminViews.agregar_producto, name='crear_producto'),
    path('admin/productos/editar_producto/<int:producto_id>/', adminViews.editar_producto, name='editar_producto'),
    path('admin/pedidos/', adminViews.lista_pedidos, name='pedidos'),
    path('admin/pedidos/actualizar_estado_pedido/<int:pedido_id>/', adminViews.actualizar_estado_pedido, name='actualizar_estado_pedido'),
    path('', homeViews.index, name='index'),
    path('promociones/', homeViews.promociones, name='promociones'),
    path('contacto/', homeViews.contacto, name='contacto'),
    path('carrito/', homeViews.carrito, name='carrito'),
    path('carrito/guardar_pedido/', homeViews.guardar_pedido, name='guardar_pedido'),
    path('productos/', homeViews.productos, name='productos'),
    path('productos/<int:producto_id>/', homeViews.ver_detalles_producto, name='ver_detalles_producto'),
    path('blog/', homeViews.blog, name='blog'),
    path('blog/alfajor/', homeViews.blogAlfajor, name='blogAlfajor'),
    path('blog/galleta_principe/', homeViews.blogGalletaPrincipe, name='blogGalletaPrincipe'),
    path('blog/galleta/', homeViews.blogGalleta, name='blogGalleta'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminPanel/models.py
import jwt
from django.conf import settings
import hashlib
from django.contrib.auth.hashers import check_password, make_password
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.utils.crypto import get_random_string
from django.utils.timezone import now
from django.conf import settings
from django.utils import timezone
import os
import secrets

class UsuarioManager(BaseUserManager):
    def create_user(self, correo, password=None, **extra_fields):
        if not correo:
            raise ValueError('El correo electrónico debe ser proporcionado')
        
        user = self.model(correo=self.normalize_email(correo), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, correo, password=None, **extra_fields):
        extra_fields.setdefault('tipo', 'admin')
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(correo, password, **extra_fields)
    
    def create_user_with_token(self, correo, password=None, **extra_fields):
        extra_fields.setdefault('_id', self.generate_id(correo, password))  # Generar _id basado en el correo
        user = self.create_user(correo, password, **extra_fields)
        user.generate_token(save_db=True)  # Generar y guardar el token en la instancia del usuario
        return user

    def generate_id(self, correo, password):
        _id_generate = password + correo  # Define tu lógica para generar _id
        return '_' + hashlib.md5(_id_generate.encode()).hexdigest()

def user_directory_path(instance, filename):
    # Generar un nombre de archivo único
    timestamp = timezone.now().strftime('%Y%m%d_%H%M%S')
    # Obtener la extensión del archivo
    extension = os.path.splitext(filename)[1]
    # Devolver la ruta de destino completa
    return os.path.join('users/img', f'{timestamp}{extension}')

class Usuario(AbstractBaseUser):
    TIPO_USUARIO_CHOICES = [
        ('admin', 'Administrador'),
        ('supervisor', 'Supervisor'),
        ('cliente', 'Cliente'),
    ]

    id = models.AutoField(primary_key=True)
    _id = models.CharField(max_length=255, unique=True)
    nombre = models.CharField(max_length=255)
    correo = models.EmailField(unique=True)
    tipo = models.CharField(max_length=10, choices=TIPO_USUARIO_CHOICES, default='cliente')
    imagen = models.ImageField(upload_to=user_directory_path, null=True, blank=True)
    token = models.CharField(max_length=1000)
    password = models.CharField(max_length=255)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    last_login = models.DateTimeField(default=None)

    objects = UsuarioManager()

    USERNAME_FIELD = 'correo'

    def save(self, *args, **kwargs):
        if not self.pk:
            self.generate_token()
        return super(Usuario, self).save(*args, **kwargs)

    def generate_token(self, save_db=False):
        # Define la información del usuario que deseas incluir en el token
        payload = {
            'id': self.id,
            '_id': self._id,
            'nombre': self.nombre,
            'correo': self.correo,
            'tipo': self.tipo,
            'imagen': str(self.imagen),
        }
        clave_secreta = settings.JWT_SECRET_KEY
        # Genera el token con una clave secreta y una fecha de expiración de 1 hora
        token = jwt.encode(payload, clave_secreta, algorithm='HS256')

        if save_db:
            self.token = token
            self.save()

        return token


    def check_password(self, password):
        return check_password(password, self.password)

    def create_admin(self):
        password = 'admin'
        _id_generate = password + 'admin@example.com'
        _id = '_' + hashlib.md5(_id_generate.encode()).hexdigest()
        password_md5 = make_password(password)
        admin, created = Usuario.objects.get_or_create(
            _id=_id,
            defaults={
                'nombre': 'Admin',
                'correo': 'admin@example.com',
                'tipo': 'admin',
                'password': password_md5,
                'last_login': now(),  # Establece last_login al momento actual
            }
        )
        if created:
            admin.generate_token()
            admin.save()
        return admin


class Producto(models.Model):
    codigo = models.CharField(max_length=255, unique=True)
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='productos/img', null=True, blank=True)
    stock = models.PositiveIntegerField()
    valor = models.DecimalField(max_digits=12, decimal_places=0)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)


class Pedido(models.Model):
    ESTADO_PEDIDO_CHOICES = [
        ('pendiente', 'Pendiente'),
        ('pagado', 'Pagado'),
        ('enviado', 'Enviado'),
        ('cancelado', 'Cancelado'),
    ]

    id = models.AutoField(primary_key=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    estado = models.CharField(max_length=10, choices=ESTADO_PEDIDO_CHOICES, default='pendiente')
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)


class DetallePedido(models.Model):
    id = models.AutoField(primary_key=True)
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    valor = models.DecimalField(max_digits=12, decimal_places=0)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)

adminPanel/views.py
import jwt
import hashlib
import json

from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

from adminPanel.models import Usuario, Producto
from .login_views import login_view, user_login
from .productos_views import countItems,agregar_producto, eliminar_producto, editar_producto, lista_pedidos, actualizar_estado_pedido
from .usuarios_views import crear_usuario, eliminar_usuario, editar_usuario
from .registro_views import registra_usuario


@login_required
def index(request):
    return render(request, 'index.html', {'request': request})

@login_required
def users(request):
    usuarios = Usuario.objects.all()
    return render(request, 'users.html', {'usuarios': usuarios})


@login_required
def productos(request):
    productos = Producto.objects.all()
    return render(request, 'productos.html', {'productos': productos})


def logout_view(request):
    logout(request)
    return redirect('/')


# Importa las vistas de login_views.py
login = login_view
user_login = user_login

# Importa las vistas de registro_views.py
registra_usuario = registra_usuario

# Importa las vistas de productos_views.py
index = countItems
agregar_producto = agregar_producto
eliminar_producto = eliminar_producto
editar_producto = editar_producto
lista_pedidos = lista_pedidos
actualizar_estado_pedido = actualizar_estado_pedido

# Importa las vistas de usuarios_views.py
crear_usuario = crear_usuario
eliminar_usuario = eliminar_usuario
editar_usuario = editar_usuario

adminPanel/templates/index.html
{% extends 'index_master.html' %}
{% block content %}
{% load static %}
<!-- page content -->
{% if request.session.tipo == 'admin' or request.session.tipo == 'supervisor' %}
  <div class="right_col" role="main">

      <section class="content">
        <div class="container-fluid">
          <!-- Info boxes -->
          <div class="row">
            <div class="col-lg-3 col-6">
              <!-- small card -->
              <div class="small-box bg-info">
                <div class="inner">
                  <h3>{{ total_productos }}</h3>

                  <p>Total de Productos</p>
                </div>
                <div class="icon">
                  <i class="fas fa-tag"></i>
                </div>
                <a href="productos/" class="small-box-footer">
                  Más info <i class="fas fa-arrow-circle-right"></i>
                </a>
              </div>
            </div>

            <div class="col-lg-3 col-6">
              <!-- small card -->
              <div class="small-box bg-warning">
                <div class="inner">
                  <h3>{{ total_usuarios }}</h3>

                  <p>Total de Usuarios</p>
                </div>
                <div class="icon">
                  <i class="fas fa-users"></i>
                </div>
                <a href="users/" class="small-box-footer">
                  Más info <i class="fas fa-arrow-circle-right"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12 col-sm-6 col-md-3">
              <div class="info-box">
                <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-shopping-cart"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Total Pedidos Pendientes</span>
                  <span class="info-box-number">
                    {{ total_pendientes }}
                    <small></small>
                  </span>
                </div>

              </div>
            </div>

            <div class="col-12 col-sm-6 col-md-3">
              <div class="info-box">
                <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-shopping-cart"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Total Pedidos en Proceso</span>
                  <span class="info-box-number">
                    {{ total_procesados }}
                    <small></small>
                  </span>
                </div>

              </div>
            </div>

            <div class="col-12 col-sm-6 col-md-3">
              <div class="info-box">
                <span class="info-box-icon bg-success elevation-1"><i class="fas fa-shopping-cart"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Total Pedidos Terminados</span>
                  <span class="info-box-number">
                    {{ total_terminados }}
                    <small></small>
                  </span>
                </div>

              </div>
            </div>

          </div>
        </div>
      </section>

      <div class="col-md-6">
        <!-- USERS LIST -->
        <div class="card">
          <div class="card-header">
            <h6 class="card-title">Ultimos 6 usuarios registrados</h6>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fas fa-minus"></i>
              </button>
              <button type="button" class="btn btn-tool" data-card-widget="remove">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body p-0">
            <ul class="users-list clearfix">
             {% for usuario in ultimos_usuarios %}
              <li>
                {% if usuario.imagen %}
                  <img src="{{ usuario.imagen.url }}" alt="Foto Usuario" width="50">
                {% else %}
                  <img src="{% static 'img/user_base.png' %}" alt="Foto Usuario" width="50">
                {% endif %}
                <a class="users-list-name">{{ usuario.nombre }}</a>
                <span class="users-list-date">{{ usuario.fecha_creacion }}</span>
              </li>
              {% endfor %}
            </ul>
            <!-- /.users-list -->
          </div>
          <!-- /.card-body -->
          <div class="card-footer text-center">
            <a href="users/">Ver todos</a>
          </div>
          <!-- /.card-footer -->
        </div>
        <!--/.card -->
      </div>

  </div>
{% endif %}

{% if request.session.tipo == 'cliente' %}
  <div class="right_col" role="main">
  </div>
{% endif %}

<!-- /page content -->
{% endblock %}

adminPanel/templates/lista_pedidos.html
{% extends 'index_master.html' %}
{% block content %}
{% load custom_filters %}
{% load static %}
  <!-- page content -->
  <div class="right_col" role="main">

    <section class="content">
        <div class="container-fluid">
            <div class="row">
            <div class="col-12">
                <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Listado de Pedidos</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                <table id="pedidoTable" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                        <th>ID</th>
                        <th>Estado</th>
                        <th>Fecha de Creación</th>
                        <th>Cliente</th>
                        <th>Correo</th>
                        <th>Total Pedido</th>
                        <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for pedido in pedidos %}
                        <tr class="{% if pedido.estado == 'pendiente' %}bg-warning{% elif pedido.estado == 'pagado' %}bg-primary{% elif pedido.estado == 'enviado' %}bg-success{% elif pedido.estado == 'cancelado' %}bg-danger{% endif %}">
                        <td>
                            <span class="pedido-id">{{ pedido.id }}</span>
                        </td>
                        <td>{{ pedido.estado }}</td>
                        <td>{{ pedido.fecha_creacion|date:"d/m/Y" }} a las {{ pedido.fecha_creacion|time:"H:i" }}</td>
                        <td>{{ pedido.usuario.nombre }}</td>
                        <td>{{ pedido.usuario.correo }}</td>
                        <td>{{ pedido.total }}</td>
                        <td>
                            <div class="actions">
                            <!-- Botón Ver Detalle -->
                            <button id="btnPedido{{ pedido.id }}" type="button" class="btn btn-sm ver-detalle-btn btn-secondary"
                                data-toggle="modal"
                                data-target="#modal{{ pedido.id }}">
                                Ver detalle
                            </button>
                            </div>
                        </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>


                </div>
                </div>
            </div>
            </div>
        </div>
    </section>

<!-- Modales de detalle de pedido -->
{% for pedido in pedidos %}
<div class="modal fade" id="modal{{ pedido.id }}" tabindex="-1" role="dialog" aria-labelledby="modal{{ pedido.id }}Label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal{{ pedido.id }}Label">Detalle del pedido #{{ pedido.id }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="invoice-container">

            <div class="invoice-header">
            <div class="row">
                <div class="col-md-6">
                <div class="invoice-title">
                    <h5>Factura</h5>
                    <p>Pedido #{{ pedido.id }}</p>
                </div>
                </div>
                <div class="col-md-6">
                <div class="invoice-info">
                    <p>Fecha de creación: {{ pedido.fecha_creacion }}</p>
                    <p>Estado: {{ pedido.estado }}</p>
                </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                <div class="invoice-user">
                    <h6>Cliente:</h6>
                    <p>{{ pedido.usuario.nombre }}</p>
                </div>
                </div>
            </div>
            </div>


          <div class="invoice-body">
            <div class="invoice-details">
                <div class="invoice-items">
                <h6>Detalle del pedido:</h6>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Precio</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for detalle in pedido.detallepedido_set.all %}
                    <tr>
                        <td>{{ detalle.producto.nombre }}</td>
                        <td>{{ detalle.cantidad }} unidades</td>
                        <td>{{ detalle.valor }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>

            </div>

            <div class="invoice-total">
            <div class="total-subtotal text-right">
                <p><span class="subtotal-label">Subtotal:</span> <span class="subtotal-value">{{ pedido.subtotal }}</span></p>
                <p><span class="subtotal-label">IVA (19%):</span> <span class="subtotal-value">{{ pedido.iva }}</span></p>
            </div>
            <div class="total-amount text-right">
                <h5>Total a pagar:</h5>
                <p class="total-value">{{ pedido.total }}</p>
            </div>
            </div>

          </div>
        </div>
      </div>

        <div class="modal-footer">
            <form method="POST" action="{% url 'actualizar_estado_pedido' pedido.id %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="estado">Estado:</label>
                    <select name="estado" id="estado" class="form-control">
                        <option value="pendiente" {% if pedido.estado == 'pendiente' %}selected{% endif %}>Pendiente</option>
                        <option value="pagado" {% if pedido.estado == 'pagado' %}selected{% endif %}>Pagado</option>
                        <option value="enviado" {% if pedido.estado == 'enviado' %}selected{% endif %}>Enviado</option>
                        <option value="cancelado" {% if pedido.estado == 'cancelado' %}selected{% endif %}>Cancelado</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>

    </div>
  </div>
</div>
{% endfor %}

 </div>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const urlParams = new URLSearchParams(window.location.search);
  const id = urlParams.get('idPedido');

  if (id) {
    const button = document.querySelector('#btnPedido' + id);
    if (button) {
      button.click();
    }
  }
});

</script>
  <!-- /page content -->
{% endblock %}